fix launch script for multiple environments
andela-sjames/Django-ReactJS-Library-App pull request #59
Opened 2018-03-01 21:55 UTC by BolajiOlajide

#### What Does This PR Do?
fix launch script for multiple environments

#### Description Of Task To Be Completed
fix launch script for multiple environments

#### Any Background Context You Want To Provide?
N/A

#### How can this be manually tested?

#### Screenshot(s)
N/A

#### What are the relevant github issues?
N/A

#### Any new frontend dependency?
N/A

#### Any new backend dependency?
N/A

2018-03-03 05:36 UTC, andela-sjames requested changes

2018-03-03 05:36 UTC, andela-sjames commented on reactlibapp/client/package.json
> +    "build": "./node_modules/.bin/webpack --config webpack.config.prod.ts -p",
What's the difference between the former and the latter? `"build": "webpack --config webpack.config.prod.ts -p"`

2018-03-03 05:36 UTC, andela-sjames commented on reactlibapp/scripts/launch.sh
> +if [ "$1" == "docker" ]; then
Let's make use of double brackets "[[ ]]" across the codebase. eg. `[[ $# -eq 0 ]]` as `[[` is a keyword rather than a builtin and is, therefore, able to offer an extended test. 

[Reference](http://mywiki.wooledge.org/BashGuide/CommandsAndArguments?highlight=keywords)

2018-03-03 12:06 UTC, BolajiOlajide commented on reactlibapp/client/package.json
> +    "build": "./node_modules/.bin/webpack --config webpack.config.prod.ts -p",
I've noticed that sometimes, if you ssh into a container and try to run some of these binary commands, if the package is not installed globally it returns `command not found` error.

This is a failsafe to ensure that doesn't happen.

2018-03-03 13:34 UTC, BolajiOlajide commented on reactlibapp/scripts/launch.sh
> +if [ "$1" == "docker" ]; then
Fixed @andela-sjames

2018-03-03 17:14 UTC, andela-pessien commented on reactlibapp/client/package.json
> +    "build": "./node_modules/.bin/webpack --config webpack.config.prod.ts -p",
That's odd - npm prepends the `node_modules/.bin` folder to `$PATH` in the context of npm scripts

2018-03-03 17:31 UTC, BolajiOlajide commented on reactlibapp/client/package.json
> +    "build": "./node_modules/.bin/webpack --config webpack.config.prod.ts -p",
Yeah! Figured myself, was surprised myself.
<img width="567" alt="screen shot 2018-03-03 at 18 31 10" src="https://user-images.githubusercontent.com/25608335/36937276-19f371da-1f11-11e8-8d93-05d13ee8d560.png">

Check out the screenshot @andela-pessien @andela-sjames

2018-03-03 17:41 UTC, andela-pessien commented on reactlibapp/client/package.json
> +    "build": "./node_modules/.bin/webpack --config webpack.config.prod.ts -p",
Oh no :P npm cannot add to the path if you're not running npm. That's why they're in npm scripts, so that npm can manage their shell contexts. Did you try actually running the scripts?

2018-03-03 18:59 UTC, BolajiOlajide commented on reactlibapp/client/package.json
> +    "build": "./node_modules/.bin/webpack --config webpack.config.prod.ts -p",
You're right. I've reversed the changes. @andela-pessien

2018-03-03 22:12 UTC, andela-pessien approved these changes
Looks good to me

2018-03-04 10:07 UTC, andela-sjames commented
@BolajiOlajide have you rebased with `develop` now?

2018-03-04 10:21 UTC, BolajiOlajide commented
Yes @andela-sjames

2018-03-04 10:21 UTC, andela-sjames approved these changes

2018-03-04 10:22 UTC, andela-sjames commented
@BolajiOlajide merge at will

2018-03-04 10:25 UTC, merged